name: Scraping & Nettoyage Immobilier

on:
  workflow_dispatch:  # permet le lancement manuel

permissions:
  contents: write

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy pandas

    - name: Run Scrapy spider
      run: scrapy crawl french_immobilier -o annonces.json

    - name: Clean data
      run: python clean_json_to_csv.py

    - name: Commit & push CSV
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add annonces_propres.csv
        git commit -m "Update CSV automatique" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
